### ISSUE TITLE
Plugin causes tests to fail

### ISSUE THREAD

**Issue by anthkris** [coreyward/gatsby-plugin-sanity-image#8]
I've setup my test environment according to the [Gatsby docs](https://www.gatsbyjs.com/docs/how-to/testing/unit-testing/) but when I try to test a component that uses this plugin, I get the following error:

```
 FAIL  src/components/__tests__/PlainCard.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /portfolio-site/node_modules/gatsby-plugin-sanity-image/index.js:2
    import {jsx} from "@emotion/core";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      3 | import styled from 'styled-components';
      4 | import PropTypes from 'prop-types';
    > 5 | import SanityImage from 'gatsby-plugin-sanity-image';
        | ^
      6 |
      7 | const PlainCardStyles = styled.a`
      8 |   background: var(--c-steely-blue);

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (src/components/PlainCard.js:5:1)
```

I've looked everywhere and most people suggest editing jest.config but it appears to be setup correctly. Any tips?

Here's my jest.config.js

```
module.exports = {
  transform: {
    '^.+\\.jsx?$': '<rootDir>/jest-preprocess.js',
    '^.+\\.js?$': '<rootDir>/jest-preprocess.js',
  },
  moduleNameMapper: {
    '.+\\.(css|styl|less|sass|scss)$': 'identity-obj-proxy',
    '.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/__mocks__/file-mock.js',
  },
  testPathIgnorePatterns: ['node_modules', '\\.cache', '<rootDir>.*/public'],
  transformIgnorePatterns: ['node_modules/(?!(gatsby)/)'],
  globals: {
    __PATH_PREFIX__: '',
  },
  testURL: 'http://localhost',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  setupFiles: ['<rootDir>/loadershim.js'],
};
```

Here's my jest-preprocess.js

```
const babelOptions = {
  presets: ['babel-preset-gatsby'],
};
module.exports = require('babel-jest').createTransformer(babelOptions);

```

**Comment by coreyward** [comment]
I believe this is because Gatsby handles ES6-style imports fine, but Jest does not. If we transpile those to `require` statements it prevents tree-shaking, but it may be possible to ship multiple outputs in the future. 

As a quick fix, you can stub `SanityImage` to return an `img` element in your tests if you’re not trying to test the functionality of gatsby-plugin-sanity-image, or configure Jest to transpile/transform code from `node_modules/gatsby-plugin-sanity-image`.

**Comment by anthkris** [comment]
Thanks for the quick response! Part of what I am trying to test is that an image exists in the document after the component is rendered. I tried adding this specifically to transformIgnorePatterns and now I get:
```
ReferenceError: __GATSBY_PLUGIN_SANITY_IMAGE__DEFAULT_IMAGE_CONFIG__ is not defined
```

Do you have an example that I might use? I've also searched the Gatsby repo (https://github.com/gatsbyjs/gatsby/issues/28727) but that doesn't appear to be working here.

**Comment by coreyward** [comment]
This error is because gatsby-plugin-sanity-image uses Webpack’s DefinePlugin to replace hardcoded references with the values you provide via options:

https://github.com/coreyward/gatsby-plugin-sanity-image/blob/9cb327bdbe8b956bc34243692eea3616090d66fd/src/gatsby-node.js#L53-L71

You could likely configure Webpack similarly through jest, but I haven't had to do that before so I'm afraid I don't have a reference for you. If you decide to use a mock, you could still return an `img` tag. If you need the image to be valid, you can do something like this: 

```jsx
import { parseImageRef } from "gatsby-plugin-sanity-image"
import sanityClient from "@sanity/client"
import sanityImageUrl from "@sanity/image-url"

const builder = sanityImageUrl(
  sanityClient({
    dataset: "your-dataset",
    projectId: "your-project-id",
    useCdn: false,
  })
)

const Img = ({ asset }) => <img src={builder.image(asset).url()} />
```

**Comment by anthkris** [comment]
Okay, thanks.

In case anyone else has this problem, here's what I did (though I'm not sure how correct it is):
```
import * as React from 'react';
import { render, screen } from '@testing-library/react';
import myComponent from '../myComponent';

jest.mock('gatsby-plugin-sanity-image', () => {
  const mockImage = () => {
    return <img src="" alt="Test" />;
  };
  return mockImage;
});

describe('PlainCard', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });
  it('renders a myComponent with an image', () => {
    render(
      <myComponent
        itemTitle={itemTitle}
        itemDesc={itemDesc}
        itemUrl={itemUrl}
        imgAsset={imgAsset}
        imgAlt="An image"
      />
    );
    // ...more test stuff
    expect(screen.getByRole('img')).toBeInTheDocument();
  });
});
```
